<?php

namespace AppBundle\Repository;

/**
 * Exmaple_classRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Exmaple_classRepository extends \Doctrine\ORM\EntityRepository
{
}
