<?php

namespace AppBundle\Repository;

/**
 * example_classRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class example_classRepository extends \Doctrine\ORM\EntityRepository
{
}
